// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UrlShortener.Infrastructure.Persistence.DataContext;

#nullable disable

namespace UrlShortener.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260323022919_CreateOutboxMessagesTable")]
    partial class CreateOutboxMessagesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UrlShortener.Application.Abstractions.TransactionalOutbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("creation_date");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("PayloadType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("payload_type");

                    b.Property<int>("ProcessedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("processed_count");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_date");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedCount")
                        .HasDatabaseName("ix_outbox_messages_processed_count");

                    b.HasIndex("ProcessedDate", "CreationDate")
                        .HasDatabaseName("ix_outbox_messages_processed_date_creation_date");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("UrlShortener.Domain.Aggregates.ShortUrls.ShortUrl", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DestinationUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("destination_url");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("short_code");

                    b.HasKey("Id")
                        .HasName("pk_short_urls");

                    b.HasIndex("ShortCode")
                        .IsUnique()
                        .HasDatabaseName("ix_short_urls_short_code");

                    b.ToTable("short_urls", (string)null);
                });

            modelBuilder.Entity("UrlShortener.Domain.Entities.Visits.Visit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Referer")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("referer");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("short_code");

                    b.Property<long>("ShortUrlId")
                        .HasColumnType("bigint")
                        .HasColumnName("short_url_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.Property<DateTime>("VisitedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("visited_at");

                    b.HasKey("Id")
                        .HasName("pk_visits");

                    b.HasIndex("ShortUrlId")
                        .HasDatabaseName("ix_visits_short_url_id");

                    b.ToTable("visits", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
